export const ACTION_LIBRARY = [
  {
    action_code: 'sales_call',
    action_name: 'Позвонить клиенту',
    action_type: 'sales_call',
    target_role: 'sales_manager',
    description: 'Связаться с клиентом и зафиксировать следующий предметный шаг.',
    trigger_conditions: ['hot_urgent', 'hot_unworked', 'decision_maker_reached'],
    expected_effect: 'Сокращение времени реакции и удержание горячей сделки в активной фазе.',
    deadline_sla_minutes: 15,
    escalation_rule: 'escalate_if_sla_breached',
    requires_approval: false,
    owner_visible: true,
  },
  {
    action_code: 'send_offer',
    action_name: 'Отправить КП',
    action_type: 'send_offer',
    target_role: 'sales_manager',
    description: 'Подготовить и отправить коммерческое предложение по подтвержденной потребности.',
    trigger_conditions: ['hot_urgent', 'money_ready'],
    expected_effect: 'Перевод сделки в стадию коммерческого оформления.',
    deadline_sla_minutes: 30,
    escalation_rule: 'escalate_if_not_sent_before_deadline',
    requires_approval: false,
    owner_visible: true,
  },
  {
    action_code: 'send_contract',
    action_name: 'Отправить договор',
    action_type: 'send_contract',
    target_role: 'sales_manager',
    description: 'Отправить договор на согласование при подтвержденной готовности клиента.',
    trigger_conditions: ['client_ready_for_contract'],
    expected_effect: 'Сокращение пути сделки до подписания.',
    deadline_sla_minutes: 60,
    escalation_rule: 'escalate_if_contract_blocked',
    requires_approval: false,
    owner_visible: true,
  },
  {
    action_code: 'clarify_specs',
    action_name: 'Уточнить техпараметры',
    action_type: 'clarify_specs',
    target_role: 'sales_manager',
    description: 'Дособрать технические параметры, которых не хватает для корректного предложения.',
    trigger_conditions: ['spec_missing', 'extraction_low_confidence'],
    expected_effect: 'Снижение риска ложной рекомендации и ошибочного подбора техники.',
    deadline_sla_minutes: 60,
    escalation_rule: 'no_escalation',
    requires_approval: false,
    owner_visible: true,
  },
  {
    action_code: 'clarify_object_access',
    action_name: 'Уточнить доступ на объект',
    action_type: 'clarify_object_access',
    target_role: 'sales_manager',
    description: 'Уточнить условия заезда, окна мобилизации и ограничения по доступу на объект.',
    trigger_conditions: ['object_access_unclear'],
    expected_effect: 'Снижение логистических рисков и срыва мобилизации.',
    deadline_sla_minutes: 45,
    escalation_rule: 'no_escalation',
    requires_approval: false,
    owner_visible: true,
  },
  {
    action_code: 'request_subrent',
    action_name: 'Передать в субаренду',
    action_type: 'request_subrent',
    target_role: 'logistics',
    description: 'Запустить подбор субарендного партнера, если собственная техника недоступна.',
    trigger_conditions: ['hot_subrent_only'],
    expected_effect: 'Сохранение сделки при дефиците своего парка.',
    deadline_sla_minutes: 30,
    escalation_rule: 'escalate_if_margin_below_threshold',
    requires_approval: false,
    owner_visible: true,
  },
  {
    action_code: 'reserve_own_equipment',
    action_name: 'Зарезервировать свою технику',
    action_type: 'reserve_own_equipment',
    target_role: 'logistics',
    description: 'Забронировать единицу собственной техники под горячую сделку.',
    trigger_conditions: ['hot_own_equipment'],
    expected_effect: 'Рост доли своей техники и защита маржи.',
    deadline_sla_minutes: 20,
    escalation_rule: 'escalate_if_conflict_with_other_object',
    requires_approval: false,
    owner_visible: true,
  },
  {
    action_code: 'reprice_deal',
    action_name: 'Пересчитать ставку',
    action_type: 'reprice_deal',
    target_role: 'sales_manager',
    description: 'Пересчитать цену сделки при низкой или пограничной марже.',
    trigger_conditions: ['low_margin_warning', 'hot_subrent_only'],
    expected_effect: 'Удержание минимальной маржи и защита прибыльности.',
    deadline_sla_minutes: 45,
    escalation_rule: 'escalate_if_manual_discount_required',
    requires_approval: false,
    owner_visible: true,
  },
  {
    action_code: 'cross_sell_offer',
    action_name: 'Предложить соседнюю технику',
    action_type: 'cross_sell_offer',
    target_role: 'sales_manager',
    description: 'Сделать кросс-продажное предложение на основе связей по объекту и спросу.',
    trigger_conditions: ['cross_sell_open'],
    expected_effect: 'Рост доли объекта и расширение корзины техники.',
    deadline_sla_minutes: 45,
    escalation_rule: 'notify_rop_if_high_value_object',
    requires_approval: false,
    owner_visible: true,
  },
  {
    action_code: 'competitor_attack',
    action_name: 'Атаковать объект конкурента',
    action_type: 'competitor_attack',
    target_role: 'rop',
    description: 'Запустить согласованный сценарий атаки объекта, где зафиксирован конкурент.',
    trigger_conditions: ['competitor_attack_window'],
    expected_effect: 'Перехват объекта и рост стратегической доли.',
    deadline_sla_minutes: 30,
    escalation_rule: 'owner_approval_required',
    requires_approval: true,
    owner_visible: true,
  },
  {
    action_code: 'owner_escalation',
    action_name: 'Эскалировать на руководителя',
    action_type: 'owner_escalation',
    target_role: 'rop',
    description: 'Передать решение на управленческий уровень при выходе за рамки стандартной политики.',
    trigger_conditions: ['hot_unworked', 'debt_risk', 'blacklist_blocked', 'low_margin_blocked'],
    expected_effect: 'Своевременное управленческое вмешательство.',
    deadline_sla_minutes: 15,
    escalation_rule: 'highest_priority',
    requires_approval: true,
    owner_visible: true,
  },
  {
    action_code: 'stop_deal',
    action_name: 'Остановить сделку',
    action_type: 'stop_deal',
    target_role: 'sales_manager',
    description: 'Остановить шумовую или убыточную сделку до появления новых оснований.',
    trigger_conditions: ['noise_low_priority', 'blacklist_blocked', 'negative_margin_blocked'],
    expected_effect: 'Освобождение ресурсов команды и снижение потерь.',
    deadline_sla_minutes: 240,
    escalation_rule: 'approval_for_stop',
    requires_approval: true,
    owner_visible: true,
  },
  {
    action_code: 'debt_control',
    action_name: 'Проверить условия оплаты',
    action_type: 'debt_control',
    target_role: 'finance_controller',
    description: 'Проверить дебиторский риск, лимиты и допустимые условия оплаты.',
    trigger_conditions: ['debt_risk'],
    expected_effect: 'Снижение риска неплатежей и просрочки.',
    deadline_sla_minutes: 60,
    escalation_rule: 'owner_if_credit_blocked',
    requires_approval: true,
    owner_visible: true,
  },
  {
    action_code: 'follow_up_reminder',
    action_name: 'Напомнить о follow-up',
    action_type: 'follow_up_reminder',
    target_role: 'sales_manager',
    description: 'Подсветить просроченное обещание менеджера и вернуть сделку в работу.',
    trigger_conditions: ['manager_promise_overdue'],
    expected_effect: 'Снижение доли сделок без движения и пропущенных касаний.',
    deadline_sla_minutes: 15,
    escalation_rule: 'escalate_if_repeated_overdue',
    requires_approval: false,
    owner_visible: true,
  },
];

export function getAction(actionCode) {
  return ACTION_LIBRARY.find((action) => action.action_code === actionCode) ?? null;
}

export function listActions() {
  return ACTION_LIBRARY.map((action) => ({ ...action }));
}
